version = 0.1

[dev.deploy.parameters]
parameter_overrides = "Stage=\"dev\" ProjectName=\"habitune-backend\" DBHost=\"REPLACE_ME_DB_HOST\" DBPort=\"REPLACE_ME_DB_PORT\" DBName=\"REPLACE_ME_DB_NAME\" DBUser=\"REPLACE_ME_DB_USER\" DBPassword=\"REPLACE_ME_DB_PASSWORD\""

[prod.deploy.parameters]
parameter_overrides = "Stage=\"prod\" ProjectName=\"habitune-backend\" DBHost=\"REPLACE_ME_DB_HOST\" DBPort=\"REPLACE_ME_DB_PORT\" DBName=\"REPLACE_ME_DB_NAME\" DBUser=\"REPLACE_ME_DB_USER\" DBPassword=\"REPLACE_ME_DB_PASSWORD\""
