version = 0.1

[dev.deploy.parameters]
parameter_overrides = "Stage=\"dev\" ProjectName=\"habitune-backend\" LogRetentionDays=\"7\""

[prod.deploy.parameters]
parameter_overrides = "Stage=\"prod\" ProjectName=\"habitune-backend\" LogRetentionDays=\"REPLACE_ME_LOG_RETENTION_DAYS\""
